name: Build APK
on:
  workflow_dispatch: # تشغيل يدوي بضغطة زر

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Create eas.json
        run: |
          echo '{
            "build": {
              "preview": {
                "android": {
                  "buildType": "apk"
                }
              }
            }
          }' > eas.json

      - name: Build APK (Internal)
        # هنا تم وضع الـ Token مباشرة كما طلبت
        run: npx eas-cli build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: "Cp-Q7QC3wAojYlUxywhfKdxPsKX1UAW8-MSKTZwY"
          
